name: 'Port of Alsea'
motto: >
    Serving the<br>
    Alsea and Yachats<br>
    waterways of the<br>
    Oregon Coast
telephone: 541-563-3872
address:
  streetAddress: '365 Port St # A'
  addressLocality: Waldport
  addressRegion: OR
  addressCountry: US
  postalCode: '97394'
social:
  facebook: portofalsea
logo: logo.png
image: DSCN2122.jpg
org_type: GovernmentOrganization
openingHours:
  -
    days: Fr-Tu
    start: '16:00'
    end: '20:30'
url: 'https://portofalsea.com'
owa:
  siteId: 3a184d88bc9ffbfa33254c63fd72eda0
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
