title: Port of Alsea
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
  - photon
  - action
metadata:
  description: 'Oregon port district covering the Alsea Bay and River corridor as well as the Yachats river'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
logo: /logo/logo.png
