color:
  key:
    hue: 215
  1:
    hueOffset: -150
  2:
    hueOffset: -44
  saturation: 33
  lightness:
    lighter: 90
    light: 75
    mid: 52
    dark: 33
    darker: 14
  foreground: '#333'
  background: '#EFEFEF'
font: Lato
font_display: 'Bree Serif'
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
