color:
  key:
    hue: 210
  1:
    hueOffset: 0
  2:
    hueOffset: 0
  saturation: 44
  lightness:
    lighter: 77
    light: 66
    mid: 44
    dark: 33
    darker: 11
  background: 'hsla(255,100%,100%,.5)'
  foreground: '#111'
font: Lato
font_display: Lato
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
